notes/urls.py
# notes/urls.py

from django.urls import path
from . import views

app_name = 'notes'

urlpatterns = [
    # 显示所有的主题
    path('topics/', views.topics, name='topics'),
    # 特定主题的详细页面
    path('topics/<topic_id>', views.topic, name='topic'),
    # 用于添加新主题的网页
    path('new_topic/', views.new_topic, name='new_topic'),
    # 用于添加新条目的页面
    path('new_entry/<topic_id>', views.new_entry, name='new_entry'),
    # 用于编辑条目的页面
    path('edit_entry/<entry_id>', views.edit_entry, name='edit_entry'),
]

notes/models.py
from django.db import models

class Topic(models.Model):
    """主题"""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text


class Entry(models.Model):
    """主题详情"""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """返回模型的字符串表示"""
        return self.text[:50] + "..."

notes/forms.py
from django import forms
from .models import Topic,Entry

class TopicForm(forms.ModelForm):
    class Meta:
        model = Topic
        fields = ['text']
        labels = {'text': ''}

class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['text']
        labels = {'text': ''}
        widgets = {'text': forms.Textarea(attrs={'cols': 165,'rows':20})} # attrs用于设置表单样式

notes/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse

from .models import Topic,Entry
from .forms import TopicForm,EntryForm

# Create your views here.

def topics(request):
    """显示所有的主题"""
    topics = Topic.objects.order_by('date_added')
    context = {'topics': topics}
    return render(request, 'notes/topics.html', context)

def topic(request, topic_id):
    """显示单个主题及其所有的条目"""
    topic = Topic.objects.get(id=topic_id)
    entries = topic.entry_set.order_by('date_added')
    context = {'topic': topic, 'entries': entries}
    return render(request, 'notes/topic.html', context)

def new_topic(request):
    """添加新主题"""
    if request.method != 'POST':
        # 未提交数据： 创建一个新表单
        form = TopicForm()
    else:
        # POST提交的数据,对数据进行处理
        form = TopicForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('notes:topics'))
    context = {'form': form}
    return render(request, 'notes/new_topic.html', context)

def new_entry(request, topic_id):
    """在特定的主题中添加新条目"""
    topic = Topic.objects.get(id=topic_id)
    if request.method != 'POST':
        # 未提交数据,创建一个空表单
        form = EntryForm()
    else:
        # POST提交的数据,对数据进行处理
        form = EntryForm(data=request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.topic = topic
            new_entry.save()
            return HttpResponseRedirect(reverse('notes:topic',args=[topic_id]))
    context = {'topic': topic, 'form': form}
    return render(request, 'notes/new_entry.html', context)

def edit_entry(request, entry_id):
    """编辑既有条目"""
    entry = Entry.objects.get(id=entry_id)
    topic = entry.topic
    if request.method != 'POST':
        # 初次请求， 使用当前条目填充表单
        form = EntryForm(instance=entry)
    else:
        # POST提交的数据， 对数据进行处理
        form = EntryForm(instance=entry, data=request.POST)
        if form.is_valid():
            form.save()
            return HttpResponseRedirect(reverse('notes:topic',args=[topic.id]))
    context = {'entry': entry, 'topic': topic, 'form': form}
    return render(request, 'notes/edit_entry.html', context)

templates/notes/edit_entry.html
{% extends "base.html" %}

{% block title %}BlackCatのTopList-知识碎片{% endblock %}

{% block content %}
  <div class="main-container">
    <div class="padding">
      <ol class="breadcrumb">
        <li><a href="/">首页</a></li>
        <li><a href="http://127.0.0.1:8000/notes/topics/">知识碎片</a></li>
        <li class="active">编辑条目</li>
      </ol>
      <div class="box">
        <div class="heading">
          <h3 class="title">编辑条目<span class="box-toggle"><i class="fa fa-chevron-up"></i></span></h3>
        </div>
        <div class="box-inner">
          <h4><a href="/notes/topics/{{topic.id}}">{{ topic }}</a> <small>编辑条目</small></h4><hr>
          <form action="/notes/edit_entry/{{topic.id}}" method="post">
            {% csrf_token %}
            {{ form.as_p }}
            <button name="submit" class="btn btn-primary" style="width:170px">保存更改</button>
          </form>
        </div>
      </div><!--box end-->
    </div>
  </div>
{% endblock content %}

templates/notes/new_entry.html
{% extends "base.html" %}

{% block title %}BlackCatのTopList-知识碎片{% endblock %}

{% block content %}
  <div class="main-container">
    <div class="padding">
      <ol class="breadcrumb">
        <li><a href="/">首页</a></li>
        <li><a href="http://127.0.0.1:8000/notes/topics/">知识碎片</a></li>
        <li class="active">添加条目</li>
      </ol>
      <div class="box">
        <div class="heading">
          <h3 class="title">添加条目<span class="box-toggle"><i class="fa fa-chevron-up"></i></span></h3>
        </div>
        <div class="box-inner">
          <h4><a href="/notes/topics/{{topic.id}}">{{ topic }}</a> <small>添加条目</small></h4><hr>
          <form action="/notes/new_entry/{{topic.id}}" method='post'>
            {% csrf_token %}
            {{ form.as_p }}
            <button name="submit" class="btn btn-primary" style="width:170px">保存更改</button>
          </form>
        </div>
      </div><!--box end-->
    </div>
  </div>
{% endblock content %}

templates/notes/new_topic.html
{% extends "base.html" %}

{% block title %}BlackCatのTopList-知识碎片{% endblock %}

{% block content %}
  <div class="main-container">
    <div class="padding">
      <ol class="breadcrumb">
        <li><a href="/">首页</a></li>
        <li><a href="http://127.0.0.1:8000/notes/topics/">知识碎片</a></li>
        <li class="active">添加主题</li>
      </ol>
      <div class="box">
        <div class="heading">
          <h3 class="title">添加主题<span class="box-toggle"><i class="fa fa-chevron-up"></i></span></h3>
        </div>
        <div class="box-inner">
          <h4>添加一个新的主题:</h4>
          <form action="{% url 'notes:new_topic' %}" method='post'>
            {% csrf_token %}
            {{ form.as_p }}
            <button name="submit" class="btn btn-primary" style="width:175px">保存更改</button>
          </form>
        </div>
      </div><!--box end-->
    </div>
  </div>
{% endblock content %}

templates/notes/topic.html
{% extends "base.html" %}

{% block title %}BlackCatのTopList-知识碎片{% endblock %}

{% block content %}
  <div class="main-container">
    <div class="padding">
      <ol class="breadcrumb">
        <li><a href="/">首页</a></li>
        <li><a href="http://127.0.0.1:8000/notes/topics/">知识碎片</a></li>
        <li class="active">主题条目</li>
      </ol>
      <div class="box">
        <div class="heading">
          <h3 class="title">主题条目<span class="box-toggle"><i class="fa fa-chevron-up"></i></span></h3>
        </div>
        <div class="box-inner">
          <h4>{{ topic }} <small><a href="/notes/new_entry/{{topic.id}}">添加条目</a></small></h4><hr>
          {% for entry in entries %}
            <div class="panel panel-default">
              <div class="panel-heading">
                <h4>
                  {{ entry.date_added|date:'Y.m.d H:i' }}
                  <small><a href="/notes/edit_entry/{{topic.id}}">编辑条目</a></small>
                </h4>
              </div>
              <div class="panel-body">
                {{ entry.text|linebreaks }}
              </div>
            </div>
          {% empty %}
            <div class="alert alert-info alert-dismissible" role="alert">
              <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
              There are no entries for this topic yet.
            </div>
          {% endfor %}
        </div>
      </div><!--box end-->
    </div>
  </div>
{% endblock content %}

templates/notes/topics.html
{% extends "base.html" %}

{% block title %}BlackCatのTopList-知识碎片{% endblock %}

{% block content %}
  <div class="main-container">
    <div class="padding">
      <ol class="breadcrumb">
        <li><a href="/">首页</a></li>
        <li class="active">知识碎片</li>
      </ol>
      <div class="box">
        <div class="heading">
          <h3 class="title">知识碎片<span class="box-toggle"><i class="fa fa-chevron-up"></i></span></h3>
        </div>
        <div class="box-inner">
          <ul>
            {% for topic in topics %}
              <div class="box">
                <li><a href="/notes/topics/{{topic.id}}" style="font-size:16px;">{{ topic }}</a></li>
              </div>
            {% empty %}
              <div class="alert alert-info alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
                No topics have been added yet.
              </div>
            {% endfor %}
          </ul>
          <button class="btn btn-primary"><a href="/notes/new_topic/" style="color: white;text-decoration:none">添加主题</a></button>
        </div>
      </div><!--box end-->
    </div>
  </div>
{% endblock content %}